#!/usr/bin/python

import os,sys 
ROOT = os.path.dirname(__file__)+'/../../'
file = open(ROOT+'src/version.py','r')
exec file
file.close() 
file = open(sys.argv[1],'a')
print >>file, 'Version:'+version
file.close()



